# Generated by Django 2.2.5 on 2021-01-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studata',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
